<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />
  <Import Project="..\..\configureawait.props" />

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>Abp.Castle.Serilog</AssemblyName>
    <PackageId>Abp.Castle.Serilog</PackageId>
    <PackageTags>asp.net;boilerplate;application framework;web framework;framework;domain driven design;serilog;castle</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <RootNamespace>Abp</RootNamespace>
    <Description>Abp.Castle.Serilog</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abp\Abp.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Castle.Core-Serilog" />
    <PackageReference Include="Castle.LoggingFacility"  />
    <PackageReference Include="Serilog"  />
    <PackageReference Include="Serilog.AspNetCore"  />
    <PackageReference Include="Serilog.Extensions.Logging"  />
    <PackageReference Include="Serilog.Settings.Configuration"  />
    <PackageReference Include="Serilog.Sinks.Console"  />
    <PackageReference Include="Serilog.Sinks.File"  />
    <PackageReference Include="Microsoft.SourceLink.GitHub" />
  </ItemGroup>


</Project>