<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />
  <Import Project="..\..\configureawait.props" />

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>Abp.Castle.Serilog</AssemblyName>
    <PackageId>Abp.Castle.Serilog</PackageId>
    <PackageTags>asp.net;boilerplate;application framework;web framework;framework;domain driven design;serilog;castle</PackageTags>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <RootNamespace>Abp</RootNamespace>
    <Description>Abp.Castle.Serilog</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Core-Serilog" Version="5.2.1" />
    <PackageReference Include="Castle.LoggingFacility" Version="6.0.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abp\Abp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Fody" Version="6.9.3" />
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="10.0.102" />
  </ItemGroup>

</Project>