<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <Import Project="..\..\configureawait.props" />
  <PropertyGroup>
    <AssemblyName>Abp.RedisCache.Tests</AssemblyName>
    <PackageId>Abp.RedisCache.Tests</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Abp.RedisCache\Abp.RedisCache.csproj" />
    <ProjectReference Include="..\..\src\Abp.RedisCache.ProtoBuf\Abp.RedisCache.ProtoBuf.csproj" />
    <ProjectReference Include="..\Abp.Tests\Abp.Tests.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Shouldly" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub"  />
  </ItemGroup>
</Project>