<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />
  <Import Project="..\..\configureawait.props" />
  <PropertyGroup>
    <AssemblyName>Abp.Dapper.Tests</AssemblyName>
    <PackageId>Abp.Dapper.Tests</PackageId>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripts\CreateInitialTables.sql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Abp.EntityFramework\Abp.EntityFramework.csproj" />
    <ProjectReference Include="..\..\src\Abp.TestBase\Abp.TestBase.csproj" />
    <ProjectReference Include="..\Abp.Tests\Abp.Tests.csproj" />
    <ProjectReference Include="..\..\src\Abp.Dapper\Abp.Dapper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="System.Data.SQLite" />
    <PackageReference Include="System.Data.SQLite.EF6" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Transactions" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" />
  </ItemGroup>

</Project>
