<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />
  <Import Project="..\..\configureawait.props" />

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>Abp</AssemblyName>
    <PackageId>Abp</PackageId>
    <PackageTags>asp.net;asp.net mvc;boilerplate;application framework;web framework;framework;domain driven design</PackageTags>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	<Description>Abp</Description>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\Sources\AbpXmlSource\*.xml;Timing\Timezone\Mapping\*.xml" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Core.AsyncInterceptor" />
	  <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" >
		  <PrivateAssets>all</PrivateAssets>
	  </PackageReference>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Castle.LoggingFacility" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Nito.AsyncEx.Context" />
    <PackageReference Include="Nito.AsyncEx.Coordination" />
    <PackageReference Include="Castle.Core" />
    <PackageReference Include="System.Configuration.ConfigurationManager" />
    <PackageReference Include="TimeZoneConverter" />
    <PackageReference Include="System.Linq.Dynamic.Core" />
  </ItemGroup>

</Project>
