<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\..\common.props" />
  <Import Project="..\..\..\configureawait.props" />
  <PropertyGroup>
    <AssemblyName>AbpAspNetCoreDemo.Core</AssemblyName>
    <PackageId>AbpAspNetCoreDemo.Core</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Localization\SourceFiles\*.json" Exclude="bin\**;obj\**;**\*.xproj;packages\**;@(EmbeddedResource)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Abp.AutoMapper\Abp.AutoMapper.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" />
  </ItemGroup>
</Project>